**Q.1- Load the dataset from sklearn. Store the data and target values in variables.**

In [7]:
import pandas as pd
import numpy as np

In [8]:
from sklearn.datasets import load_wine
wine = load_wine()

In [9]:
x = wine.data
y = wine.target

**Q.2- Perform the following ensemble methods and print the accuracy:**<br>
**(a)Bagged Decision Trees**

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test =  train_test_split(x,y,random_state=0,test_size=0.25)

In [11]:
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.ensemble import BaggingClassifier 
bbc = BaggingClassifier(random_state=42)
bbc.fit(X_train, Y_train)
y_pred = bbc.predict(X_test)
print(confusion_matrix(Y_test, y_pred))

[[16  0  0]
 [ 0 20  1]
 [ 1  0  7]]


In [12]:
accuracy_score(Y_test,y_pred)

0.9555555555555556

**(b)Random Forest Classification**

In [13]:
from sklearn.ensemble import RandomForestClassifier

In [14]:
clf = RandomForestClassifier(max_depth=2, random_state=0)
clf.fit(X_train, Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=2, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [15]:
y_pr = clf.predict(X_test)


In [16]:
accuracy_score(Y_test,y_pr)

0.9555555555555556

In [28]:
confusion_matrix(Y_test,y_pr)

array([[16,  0,  0],
       [ 1, 19,  1],
       [ 0,  0,  8]], dtype=int64)

**(c)Stochastic Gradient Boosting Classification**

In [17]:
from sklearn.ensemble import GradientBoostingClassifier

In [18]:
gbc = GradientBoostingClassifier()
gbc.fit(X_train, Y_train)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=100,
              presort='auto', random_state=None, subsample=1.0, verbose=0,
              warm_start=False)

In [19]:
y_p = gbc.predict(X_test)

In [20]:
accuracy_score(Y_test,y_p)

0.9555555555555556

In [21]:
confusion_matrix(Y_test,y_p)

array([[16,  0,  0],
       [ 1, 19,  1],
       [ 0,  0,  8]], dtype=int64)

**(d)Voting Ensemble (Decision Tree, Logistic Regression, SVM)**

In [27]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier

In [28]:
ob1 = LogisticRegression()
ob2 = DecisionTreeClassifier(criterion='gini')
ob3 = SVC(kernel='rbf')

In [29]:
est = VotingClassifier(estimators=[('lr', ob1), ('dt', ob2), ('svm', ob3)], voting='hard')

In [30]:
est.fit(X_train,Y_train)

VotingClassifier(estimators=[('lr', LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)), ('dt', Decisio...,
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False))],
         flatten_transform=None, n_jobs=1, voting='hard', weights=None)

In [31]:
y_pred3 = est.predict(X_test)

C:\ProgramData\Anaconda31\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [34]:
accuracy_score(Y_test, y_pred3)

0.9333333333333333